package com.sample

import com.sample.hello.Message

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        m: Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Finish : [" + myMessage + "]" );
        m.setStatus( Message.FINISH );
        update( m );
end
